"use client";

import { useMemo } from "react";
import Link from "next/link";
import { Bot, Circle, FileSearch, KeyRound, Play, Radar, Video } from "lucide-react";
import {
  Badge,
  Button,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  Progress,
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@/components/ui";
import {
  CodeBlock,
  CopyButton,
  DataTable,
  EmptyState,
  ErrorState,
  LoadingState,
  StatusBadge,
} from "@/components/shared";
import { routes } from "@/config/nav";
import { formatDuration, formatPercent } from "@/lib/utils";
import type { Column } from "@/components/shared";
import type { Assertion, FlakyTest, TestCase } from "@/lib/api/types";

/** Provenance is the point of the marker: who wrote this test, agent or human. */
const SOURCE_META: Record<
  NonNullable<TestCase["generatedBy"]>,
  { label: string; icon: typeof Bot; variant: "primary" | "info" | "muted" }
> = {
  agent: { label: "Generated by agent", icon: Bot, variant: "primary" },
  recording: { label: "Recorded", icon: Video, variant: "info" },
  human: { label: "Hand-written", icon: KeyRound, variant: "muted" },
};

const ASSERTION_COLUMNS: Column<Assertion>[] = [
  {
    id: "kind",
    header: "Kind",
    width: "96px",
    cell: (row) => (
      <Badge variant="outline" size="xs">
        {row.kind}
      </Badge>
    ),
  },
  {
    id: "target",
    header: "Target",
    width: "minmax(0,1.4fr)",
    cell: (row) => (
      <span className="text-code truncate text-muted-foreground" title={row.target}>
        {row.target}
      </span>
    ),
  },
  {
    id: "expected",
    header: "Expected",
    width: "minmax(0,1.6fr)",
    cell: (row) => (
      <span className="truncate" title={row.expected}>
        {row.expected}
      </span>
    ),
  },
  {
    id: "soft",
    header: "Soft",
    width: "64px",
    align: "center",
    cell: (row) =>
      row.soft ? (
        <Badge variant="warning" size="xs">
          soft
        </Badge>
      ) : (
        <span className="text-subtle-foreground">—</span>
      ),
  },
];

/** `steps[].code` is already a Playwright line; the wrapper is what is missing. */
function toPlaywrightSpec(testCase: TestCase): string {
  const escaped = testCase.title.replace(/'/g, "\\'");
  const body = testCase.steps
    .slice()
    .sort((a, b) => a.index - b.index)
    .map((step) => `  ${step.code.replace(/;$/, "")};`)
    .join("\n");

  return [
    "import { test, expect } from '@playwright/test';",
    "",
    `// ${testCase.id} · ${testCase.file}`,
    `test('${escaped}', async ({ page }) => {`,
    body,
    "});",
    "",
  ].join("\n");
}

export interface CaseDetailProps {
  /** `null` means the id resolved to nothing in the active data source. */
  testCase: TestCase | null | undefined;
  caseId: string;
  suiteName?: string;
  flake?: FlakyTest;
  loading?: boolean;
  error?: unknown;
  onRetry?: () => void;
  onRun: (caseId: string) => void;
  running?: boolean;
  /** Strips `?case=` — the recovery action for an unresolvable id. */
  onClear: () => void;
}

export function CaseDetail({
  testCase,
  caseId,
  suiteName,
  flake,
  loading = false,
  error,
  onRetry,
  onRun,
  running = false,
  onClear,
}: CaseDetailProps) {
  const spec = useMemo(() => (testCase ? toPlaywrightSpec(testCase) : ""), [testCase]);
  const steps = useMemo(
    () => (testCase ? testCase.steps.slice().sort((a, b) => a.index - b.index) : []),
    [testCase],
  );

  if (error) {
    return (
      <>
        <DrawerHeader>
          <DrawerTitle>Case unavailable</DrawerTitle>
        </DrawerHeader>
        <ErrorState error={error} onRetry={onRetry} testId="case-detail-error" />
      </>
    );
  }

  if (loading) {
    return (
      <>
        <DrawerHeader>
          <DrawerTitle>Loading case…</DrawerTitle>
        </DrawerHeader>
        <LoadingState rows={5} variant="panel" />
      </>
    );
  }

  if (!testCase) {
    return (
      <>
        <DrawerHeader>
          <DrawerTitle>Case not found</DrawerTitle>
        </DrawerHeader>
        <EmptyState
          icon={FileSearch}
          title="Case not found in this data source"
          description={`No case with id "${caseId}" exists under the active adapter. It may live in another project, or the data source was switched.`}
          action={
            <Button variant="outline" onClick={onClear} data-testid="case-detail-clear">
              Clear selection
            </Button>
          }
          testId="case-detail-empty"
        />
      </>
    );
  }

  const source = SOURCE_META[testCase.generatedBy ?? "human"];
  const SourceIcon = source.icon;

  return (
    <div data-testid="case-detail" className="flex min-h-0 flex-1 flex-col gap-3">
      <DrawerHeader>
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-code text-muted-foreground">{testCase.id}</span>
          <StatusBadge status={testCase.status} size="xs" />
          <Badge
            variant={source.variant}
            size="xs"
            data-testid={`case-detail-source-${testCase.generatedBy ?? "human"}`}
          >
            <SourceIcon className="size-3" aria-hidden />
            {source.label}
          </Badge>
        </div>
        <DrawerTitle>{testCase.title}</DrawerTitle>

        <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-muted-foreground">
          <span className="text-code truncate" title={testCase.file}>
            {testCase.file}
          </span>
          <span className="font-mono tabular-nums">{formatDuration(testCase.durationMs)}</span>
          <span>{testCase.lastRun}</span>
          <span>
            Owner <span className="text-foreground">{testCase.owner}</span>
          </span>
          {suiteName ? (
            <Link
              href={routes.cases({ suiteId: testCase.suiteId })}
              className="text-primary underline-offset-2 hover:underline"
              data-testid="case-detail-suite-link"
            >
              {suiteName}
            </Link>
          ) : null}
        </div>

        {testCase.tags.length ? (
          <div className="flex flex-wrap gap-1 pt-0.5">
            {testCase.tags.map((tag) => (
              <Link key={tag} href={routes.cases({ tag })} data-testid={`case-detail-tag-${tag}`}>
                <Badge variant="muted" size="xs" className="hover:text-foreground">
                  {tag}
                </Badge>
              </Link>
            ))}
          </div>
        ) : null}
      </DrawerHeader>

      <Tabs defaultValue="steps" className="min-h-0 flex-1">
        <TabsList data-testid="case-detail-tabs">
          <TabsTrigger value="steps" data-testid="case-detail-tab-steps">
            Steps
            <Badge variant="muted" size="xs">
              {steps.length}
            </Badge>
          </TabsTrigger>
          <TabsTrigger value="assertions" data-testid="case-detail-tab-assertions">
            Assertions
            <Badge variant="muted" size="xs">
              {testCase.assertions.length}
            </Badge>
          </TabsTrigger>
          <TabsTrigger value="locator" data-testid="case-detail-tab-locator">
            Locator
          </TabsTrigger>
          <TabsTrigger value="flake" data-testid="case-detail-tab-flake">
            Flake
          </TabsTrigger>
        </TabsList>

        <TabsContent
          value="steps"
          className="min-h-0 flex-1 overflow-y-auto pr-1"
          data-testid="case-detail-steps"
        >
          {steps.length === 0 ? (
            <EmptyState
              title="No steps recorded"
              description="This case has no step trace under the active data source."
              testId="case-detail-steps-empty"
            />
          ) : (
            <ol className="flex flex-col gap-2.5">
              {steps.map((step) => {
                const masked = Boolean(step.value?.startsWith("•"));
                return (
                  <li
                    key={step.id}
                    data-testid={`case-detail-step-${step.index}`}
                    className="surface-inset flex gap-2.5 rounded-[var(--radius-md)] p-2.5"
                  >
                    <span
                      aria-hidden
                      className="mt-0.5 grid size-5 shrink-0 place-items-center rounded-full border border-border bg-elevated font-mono text-[10px] tabular-nums text-muted-foreground"
                    >
                      {step.index}
                    </span>
                    <div className="flex min-w-0 flex-1 flex-col gap-1.5">
                      <div className="flex flex-wrap items-center gap-2">
                        <Badge variant="outline" size="xs">
                          {step.action}
                        </Badge>
                        <span className="text-code truncate text-muted-foreground" title={step.target}>
                          {step.target}
                        </span>
                        {step.value === undefined ? null : (
                          <span
                            className="text-code truncate text-foreground"
                            title={masked ? "Masked secret" : step.value}
                          >
                            {masked ? (
                              <span className="inline-flex items-center gap-1 text-waiting">
                                <KeyRound className="size-3" aria-hidden />
                                masked
                              </span>
                            ) : (
                              step.value
                            )}
                          </span>
                        )}
                      </div>
                      <CodeBlock code={step.code} language="ts" maxHeight={120} />
                    </div>
                  </li>
                );
              })}
            </ol>
          )}
        </TabsContent>

        <TabsContent
          value="assertions"
          className="min-h-0 flex-1 overflow-y-auto pr-1"
          data-testid="case-detail-assertions"
        >
          <DataTable
            rows={testCase.assertions}
            columns={ASSERTION_COLUMNS}
            rowKey={(row) => row.id}
            testId="case-detail-assertions-table"
            empty={
              <EmptyState
                title="No assertions"
                description="The case runs steps but asserts nothing — worth flagging in review."
                testId="case-detail-assertions-empty"
              />
            }
          />
        </TabsContent>

        <TabsContent
          value="locator"
          className="flex min-h-0 flex-1 flex-col gap-3 overflow-y-auto pr-1"
          data-testid="case-detail-locator"
        >
          <div className="flex flex-col gap-1.5">
            <span className="label-mono">Primary locator</span>
            <CodeBlock code={testCase.primaryLocator} language="ts" />
          </div>
          <div className="flex flex-col gap-1.5">
            <span className="label-mono">Playwright spec</span>
            <CodeBlock code={spec} language="ts" filename={testCase.file} lineNumbers />
          </div>
          <Button variant="outline" asChild data-testid="case-detail-open-inspector">
            <Link href={routes.workbench()}>
              <Radar className="size-3.5" aria-hidden />
              Open in inspector
            </Link>
          </Button>
        </TabsContent>

        <TabsContent
          value="flake"
          className="min-h-0 flex-1 overflow-y-auto pr-1"
          data-testid="case-detail-flake"
        >
          {flake ? (
            <div className="flex flex-col gap-3">
              <div className="surface-inset flex flex-col gap-2 rounded-[var(--radius-md)] p-3">
                <div className="flex items-center justify-between gap-3">
                  <span className="label-mono">Flake rate</span>
                  <span className="font-mono text-sm font-semibold tabular-nums text-waiting">
                    {formatPercent(flake.flakeRate)}
                  </span>
                </div>
                <Progress value={flake.flakeRate * 100} tone="warning" />
                <div className="flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-muted-foreground">
                  <span>
                    Runs affected{" "}
                    <span className="font-mono tabular-nums text-foreground">
                      {flake.runsAffected}
                    </span>
                  </span>
                  <span>
                    Last failure <span className="text-foreground">{flake.lastFailure}</span>
                  </span>
                  <span className="text-code truncate">{flake.file}</span>
                </div>
              </div>
              <div className="flex flex-col gap-1.5">
                <span className="label-mono">Suspected cause</span>
                <p className="text-xs leading-relaxed text-muted-foreground">
                  {flake.suspectedCause}
                </p>
              </div>
              <Button variant="outline" asChild data-testid="case-detail-flake-runs">
                <Link href={routes.runs()}>
                  <Radar className="size-3.5" aria-hidden />
                  See flake analysis in runs
                </Link>
              </Button>
            </div>
          ) : (
            <EmptyState
              icon={Circle}
              title="Not on the flake list"
              description={
                testCase.flakeRate > 0
                  ? `This case reports a ${formatPercent(testCase.flakeRate)} flake rate but has no entry in the flake analysis yet.`
                  : "No retries or intermittent failures recorded for this case."
              }
              action={
                <Button variant="outline" asChild>
                  <Link href={routes.runs()}>Open runs</Link>
                </Button>
              }
              testId="case-detail-flake-empty"
            />
          )}
        </TabsContent>
      </Tabs>

      <DrawerFooter className="flex-wrap justify-start">
        <Button
          variant="primary"
          onClick={() => onRun(testCase.id)}
          loading={running}
          data-testid="case-detail-run"
        >
          <Play className="size-3.5" aria-hidden />
          Run this case
        </Button>
        <Button variant="outline" asChild data-testid="case-detail-workbench">
          <Link href={routes.workbench()}>
            <Bot className="size-3.5" aria-hidden />
            Open in workbench
          </Link>
        </Button>
        <CopyButton value={spec} label="Copy as Playwright spec" testId="case-detail-copy-spec" />
        <Button variant="ghost" asChild data-testid="case-detail-view-suite">
          <Link href={routes.suites()}>View suite</Link>
        </Button>
      </DrawerFooter>
    </div>
  );
}
